### ISSUE TITLE
删除组织的时候，没有做数据校验

### ISSUE THREAD

**Issue by etherfurnace** [WeOps-Lab/weops_lite#1]
问题：
* 删除组织的时候，没有做数据校验

预期：
* 删除组织、角色的时候，要做数据校验，假如角色下有组织，组织下有用户或者角色的时候，不能删除

注意：
* 对`组织`、`角色`、`用户`、`权限` 进行检查，统一修复
<img width="1274" alt="企业微信截图_1707200839252" src="https://github.com/WeOps-Lab/weops_lite/assets/81210463/9060352c-8722-4520-be23-63875f9130eb">

**Comment by baiyf-git** [comment]
问题已经修复，commit为：8ec441c
附链接如下：
https://github.com/WeOps-Lab/weops_lite/commit/8ec441c88e8d00b0cd7110f98da305128f7574b6
