### ISSUE TITLE
用户权限配置，数据不一致，在用户绑定了角色、组织，但是在组织那看不到

### ISSUE THREAD

**Issue by etherfurnace** [WeOps-Lab/weops_lite#2]
问题：
* 用户权限配置，数据不一致，在用户绑定了角色、组织，但是在组织那看不到

期望：
* 用户、组织、角色 的数据返回应该一致

<img width="1274" alt="企业微信截图_17072010765707" src="https://github.com/WeOps-Lab/weops_lite/assets/81210463/224d84ca-ccef-4ceb-b2fb-fe9e1674fe20">

<img width="1275" alt="企业微信截图_17072010928270" src="https://github.com/WeOps-Lab/weops_lite/assets/81210463/640729b2-371b-47f0-8d91-0e20b0bb0852">

**Comment by baiyf-git** [comment]
问题已修复，commit为:1a090fe
附链接如下：
https://github.com/WeOps-Lab/weops_lite/commit/1a090fea87bb024725bcef342bec785fa84fa67a
