### ISSUE TITLE
设置了用户角色，角色也绑定了菜单，但是切换用户登陆之后，没有拿到任何的菜单

### ISSUE THREAD

**Issue by etherfurnace** [WeOps-Lab/weops_lite#3]
问题：
* 设置了用户角色，角色也绑定了菜单，但是切换用户登陆之后，没有拿到任何的菜单，并且用户没有获取到任何权限

<img width="1274" alt="企业微信截图_17072012067341" src="https://github.com/WeOps-Lab/weops_lite/assets/81210463/3af52815-ab7e-45dd-9f97-4fddf3e6b46c">

**Comment by baiyf-git** [comment]
问题已修复，commit为：870e583
附链接如下：
https://github.com/WeOps-Lab/weops_lite/commit/870e583e29f31e9a700e73b8b8e7e8bc3c3554d4
